obj-$(CONFIG_USB_BLUETOOTH)	+= entavio.o
#entavio-y	:= ../../../../../../package/settop/bchs/drivers/scheduler/output/default/lib/LinuxKernel-2.6-mips/libsched.a
entavio-objs	+= usb_com.o usb_dfu.o usb_intf.o usb_queue.o bt_usb_main.o sched.o

